// <auto-generated />
using Beca.PlaylistInfo.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beca.PlaylistInfo.API.Migrations
{
    [DbContext(typeof(PlaylistInfoContext))]
    [Migration("20221109085430_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Beca.PlaylistInfo.API.Entities.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The one with that big park.",
                            Title = "Playlist 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The one with the cathedral that was never really finished.",
                            Title = "Playlist 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The one with that big tower.",
                            Title = "Playlist 3"
                        });
                });

            modelBuilder.Entity("Beca.PlaylistInfo.API.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The most visited urban park in the United States.",
                            PlaylistId = 1,
                            Title = "Song 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A 102-story skyscraper located in Midtown Manhattan.",
                            PlaylistId = 1,
                            Title = "Song 3"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A Gothic style cathedral, conceived by architects Jan and Pieter Appelmans.",
                            PlaylistId = 2,
                            Title = "Song 4"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The the finest example of railway architecture in Belgium.",
                            PlaylistId = 2,
                            Title = "Song 5"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A wrought iron lattice tower on the Champ de Mars, named after engineer Gustave Eiffel.",
                            PlaylistId = 3,
                            Title = "Song 6"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The world's largest museum.",
                            PlaylistId = 3,
                            Title = "Song 7"
                        });
                });

            modelBuilder.Entity("Beca.PlaylistInfo.API.Entities.Song", b =>
                {
                    b.HasOne("Beca.PlaylistInfo.API.Entities.Playlist", "Playlist")
                        .WithMany("Songs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Beca.PlaylistInfo.API.Entities.Playlist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
